// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Geteventsuntil
{
    /// <summary>
    /// Builds and executes requests for operations under \geteventsuntil
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GeteventsuntilRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GeteventsuntilRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/geteventsuntil?event_id={event_id}&home_id={home_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GeteventsuntilRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/geteventsuntil?event_id={event_id}&home_id={home_id}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the snapshot associated to an event.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAWelcomeEventResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NAWelcomeEventResponse?> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder.GeteventsuntilRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NAWelcomeEventResponse> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder.GeteventsuntilRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NAWelcomeEventResponse>(requestInfo, global::NetatmoClient.Models.NAWelcomeEventResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the snapshot associated to an event.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder.GeteventsuntilRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder.GeteventsuntilRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the snapshot associated to an event.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GeteventsuntilRequestBuilderGetQueryParameters 
        {
            /// <summary>Your request will retrieve all the events until this one</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("event_id")]
            public string? EventId { get; set; }
#nullable restore
#else
            [QueryParameter("event_id")]
            public string EventId { get; set; }
#endif
            /// <summary>ID of the Home you&apos;re interested in</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("home_id")]
            public string? HomeId { get; set; }
#nullable restore
#else
            [QueryParameter("home_id")]
            public string HomeId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
