// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using NetatmoClient.Addwebhook;
using NetatmoClient.Createnewschedule;
using NetatmoClient.Devicelist;
using NetatmoClient.Dropwebhook;
using NetatmoClient.Getcamerapicture;
using NetatmoClient.Geteventsuntil;
using NetatmoClient.Gethomecoachsdata;
using NetatmoClient.Gethomedata;
using NetatmoClient.Getlasteventof;
using NetatmoClient.Getmeasure;
using NetatmoClient.Getnextevents;
using NetatmoClient.Getpublicdata;
using NetatmoClient.Getstationsdata;
using NetatmoClient.Getthermostatsdata;
using NetatmoClient.Getthermstate;
using NetatmoClient.Getuser;
using NetatmoClient.Partnerdevices;
using NetatmoClient.Setpersonsaway;
using NetatmoClient.Setpersonshome;
using NetatmoClient.Setthermpoint;
using NetatmoClient.Switchschedule;
using NetatmoClient.Syncschedule;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;

namespace NetatmoClient;

public partial class NetatmoClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class NetatmoBaseClient : BaseRequestBuilder
    {
        /// <summary>The addwebhook property</summary>
        public global::NetatmoClient.Addwebhook.AddwebhookRequestBuilder Addwebhook
        {
            get => new global::NetatmoClient.Addwebhook.AddwebhookRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The createnewschedule property</summary>
        public global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder Createnewschedule
        {
            get =>
                new global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The devicelist property</summary>
        public global::NetatmoClient.Devicelist.DevicelistRequestBuilder Devicelist
        {
            get => new global::NetatmoClient.Devicelist.DevicelistRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The dropwebhook property</summary>
        public global::NetatmoClient.Dropwebhook.DropwebhookRequestBuilder Dropwebhook
        {
            get => new global::NetatmoClient.Dropwebhook.DropwebhookRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The getcamerapicture property</summary>
        public global::NetatmoClient.Getcamerapicture.GetcamerapictureRequestBuilder Getcamerapicture
        {
            get => new global::NetatmoClient.Getcamerapicture.GetcamerapictureRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The geteventsuntil property</summary>
        public global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder Geteventsuntil
        {
            get => new global::NetatmoClient.Geteventsuntil.GeteventsuntilRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The gethomecoachsdata property</summary>
        public global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder Gethomecoachsdata
        {
            get =>
                new global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The gethomedata property</summary>
        public global::NetatmoClient.Gethomedata.GethomedataRequestBuilder Gethomedata
        {
            get => new global::NetatmoClient.Gethomedata.GethomedataRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The getlasteventof property</summary>
        public global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder Getlasteventof
        {
            get => new global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The getmeasure property</summary>
        public global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder Getmeasure
        {
            get => new global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The getnextevents property</summary>
        public global::NetatmoClient.Getnextevents.GetnexteventsRequestBuilder Getnextevents
        {
            get => new global::NetatmoClient.Getnextevents.GetnexteventsRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The getpublicdata property</summary>
        public global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder Getpublicdata
        {
            get => new global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The getstationsdata property</summary>
        public global::NetatmoClient.Getstationsdata.GetstationsdataRequestBuilder Getstationsdata
        {
            get => new global::NetatmoClient.Getstationsdata.GetstationsdataRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The getthermostatsdata property</summary>
        public global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder Getthermostatsdata
        {
            get => new global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder(PathParameters,
                RequestAdapter);
        }

        /// <summary>The getthermstate property</summary>
        public global::NetatmoClient.Getthermstate.GetthermstateRequestBuilder Getthermstate
        {
            get => new global::NetatmoClient.Getthermstate.GetthermstateRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The getuser property</summary>
        public global::NetatmoClient.Getuser.GetuserRequestBuilder Getuser
        {
            get => new global::NetatmoClient.Getuser.GetuserRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The partnerdevices property</summary>
        public global::NetatmoClient.Partnerdevices.PartnerdevicesRequestBuilder Partnerdevices
        {
            get => new global::NetatmoClient.Partnerdevices.PartnerdevicesRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The setpersonsaway property</summary>
        public global::NetatmoClient.Setpersonsaway.SetpersonsawayRequestBuilder Setpersonsaway
        {
            get => new global::NetatmoClient.Setpersonsaway.SetpersonsawayRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The setpersonshome property</summary>
        public global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder Setpersonshome
        {
            get => new global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The setthermpoint property</summary>
        public global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder Setthermpoint
        {
            get => new global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The switchschedule property</summary>
        public global::NetatmoClient.Switchschedule.SwitchscheduleRequestBuilder Switchschedule
        {
            get => new global::NetatmoClient.Switchschedule.SwitchscheduleRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>The syncschedule property</summary>
        public global::NetatmoClient.Syncschedule.SyncscheduleRequestBuilder Syncschedule
        {
            get => new global::NetatmoClient.Syncschedule.SyncscheduleRequestBuilder(PathParameters, RequestAdapter);
        }

        /// <summary>
        /// Instantiates a new <see cref="NetatmoClient.NetatmoBaseClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NetatmoBaseClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}",
            new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();

            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.netatmo.com/api";
            }

            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
