// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Getmeasure
{
    /// <summary>
    /// Builds and executes requests for operations under \getmeasure
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetmeasureRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetmeasureRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getmeasure?device_id={device_id}&scale={scale}&type={type}{&date_begin*,date_end*,limit*,module_id*,optimize*,real_time*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetmeasureRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getmeasure?device_id={device_id}&scale={scale}&type={type}{&date_begin*,date_end*,limit*,module_id*,optimize*,real_time*}", rawUrl)
        {
        }
        /// <summary>
        /// The method getmeasure returns the measurements of a device or a module.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAMeasureResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NAMeasureResponse?> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder.GetmeasureRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NAMeasureResponse> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder.GetmeasureRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NAMeasureResponse>(requestInfo, global::NetatmoClient.Models.NAMeasureResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The method getmeasure returns the measurements of a device or a module.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder.GetmeasureRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder.GetmeasureRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Getmeasure.GetmeasureRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// The method getmeasure returns the measurements of a device or a module.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetmeasureRequestBuilderGetQueryParameters 
        {
            /// <summary>Starting timestamp (utc) of the requested measurements.Please note measurement retrieving is limited to 1024 measurements.</summary>
            [QueryParameter("date_begin")]
            public int? DateBegin { get; set; }
            /// <summary>Ending timestamp (utc) of the request measurements.If you want only the last measurement, do not provide date_begin, and set date_end to `last`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("date_end")]
            public string? DateEnd { get; set; }
#nullable restore
#else
            [QueryParameter("date_end")]
            public string DateEnd { get; set; }
#endif
            /// <summary>Id of the device whose module&apos;s measurements you want to retrieve. This _id can be found in the user&apos;s devices field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("device_id")]
            public string? DeviceId { get; set; }
#nullable restore
#else
            [QueryParameter("device_id")]
            public string DeviceId { get; set; }
#endif
            /// <summary>Limits the number of measurements returned (default &amp; max is 1024)</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>If you don&apos;t specify any module_id you will retrieve the device&apos;s measurements. If you specify a module_id you will retrieve the module&apos;s measurements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("module_id")]
            public string? ModuleId { get; set; }
#nullable restore
#else
            [QueryParameter("module_id")]
            public string ModuleId { get; set; }
#endif
            /// <summary>Allows you to choose the format of the answer.If you build a mobile app and bandwith usage is an issue, use `optimize = true`.Use `optimize = false`, for an easier parse. In this case, values are indexed by sorted timestamp.Example of un-optimized response :```json{&quot;status&quot;: &quot;ok&quot;,   &quot;body&quot;: {    &quot;1347575400&quot;: [18.3,39],    &quot;1347586200&quot;: [20.6,48]  },&quot;time_exec&quot;: 0.012136936187744}```If optimize is set true, measurements are returned as an array of series of regularly spaced measurements. Each series is defined by a beginning time beg_time and a step between measurements, step_time:```json{&quot;status&quot;: &quot;ok&quot;,  &quot;body&quot;: [    {&quot;beg_time&quot;: 1347575400,     &quot;step_time&quot;: 10800,     &quot;value&quot;:         [[18.3,39],        [ 20.6,48]]    }],&quot;time_exec&quot;: 0.014238119125366}```Default value is `true`.</summary>
            [QueryParameter("optimize")]
            public bool? Optimize { get; set; }
            /// <summary>In scales higher than max, since the data is aggregated, the timestamps returned are by default offset by +(scale/2).For instance, if you ask for measurements at a daily scale, you will receive data timestamped at 12:00 if real_time is set to `false` (default case), and timestamped at 00:00 if real_time is set to `true`.NB : The servers always store data with real_time set to `true` and data are offset by this parameter AFTER having being time-filtered, thus you could have data after date_end if real_time is set to `false`.</summary>
            [QueryParameter("real_time")]
            public bool? RealTime { get; set; }
            /// <summary>Defines the time interval between two measurements.Possible values :max -&gt; every value stored will be returned30min -&gt; 1 value every 30 minutes1hour -&gt; 1 value every hour3hours -&gt; 1 value every 3 hours1day -&gt; 1 value per day1week -&gt; 1 value per week1month -&gt; 1 value per month</summary>
            [QueryParameter("scale")]
            public global::NetatmoClient.Getmeasure.GetScaleQueryParameterType? Scale { get; set; }
            /// <summary>Measures you are interested in. Data you can request depends on the scale.**For Weather Station:**  * max -&gt; Temperature (°C), CO2 (ppm), Humidity (%), Pressure (mbar), Noise (db), Rain (mm), WindStrength (km/h), WindAngle (angles), Guststrength (km/h), GustAngle (angles)  * 30min, 1hour, 3hours -&gt; Same as above + min_temp, max_temp, min_hum, max_hum, min_pressure, max_pressure, min_noise, max_noise, sum_rain, date_max_gust  * 1day, 1week, 1month -&gt; Same as above + date_min_temp, date_max_temp, date_min_hum, date_max_hum, date_min_pressure, date_max_pressure, date_min_noise, date_max_noise, date_min_co2, date_max_co2**For Thermostat:**  * max -&gt; temperature (°C), sp_temperature (°C), boileron (sec), boileroff (sec)  * 30min, 1hour, 3hours -&gt; temperature, sp_temperature, min_temp,max_temp, sum_boiler_on, sum_boiler_off  * 1day, 1week, 1month -&gt; temperature, min_temp, date_min_temp,max_temp, sum_boiler_on, sum_boiler_off</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public global::NetatmoClient.Getmeasure.GetTypeQueryParameterType[]? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public global::NetatmoClient.Getmeasure.GetTypeQueryParameterType[] Type { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
