// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NetatmoClient.Getmeasure
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetScaleQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "max")]
        #pragma warning disable CS1591
        Max,
        #pragma warning restore CS1591
        [EnumMember(Value = "30min")]
        #pragma warning disable CS1591
        ThreeZeromin,
        #pragma warning restore CS1591
        [EnumMember(Value = "1hour")]
        #pragma warning disable CS1591
        Onehour,
        #pragma warning restore CS1591
        [EnumMember(Value = "3hours")]
        #pragma warning disable CS1591
        Threehours,
        #pragma warning restore CS1591
        [EnumMember(Value = "1day")]
        #pragma warning disable CS1591
        Oneday,
        #pragma warning restore CS1591
        [EnumMember(Value = "1week")]
        #pragma warning disable CS1591
        Oneweek,
        #pragma warning restore CS1591
        [EnumMember(Value = "1month")]
        #pragma warning disable CS1591
        Onemonth,
        #pragma warning restore CS1591
    }
}
