// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NetatmoClient.Getmeasure
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Temperature")]
        #pragma warning disable CS1591
        Temperature,
        #pragma warning restore CS1591
        [EnumMember(Value = "CO2")]
        #pragma warning disable CS1591
        CO2,
        #pragma warning restore CS1591
        [EnumMember(Value = "Humidity")]
        #pragma warning disable CS1591
        Humidity,
        #pragma warning restore CS1591
        [EnumMember(Value = "Pressure")]
        #pragma warning disable CS1591
        Pressure,
        #pragma warning restore CS1591
        [EnumMember(Value = "Noise")]
        #pragma warning disable CS1591
        Noise,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rain")]
        #pragma warning disable CS1591
        Rain,
        #pragma warning restore CS1591
        [EnumMember(Value = "WindStrength")]
        #pragma warning disable CS1591
        WindStrength,
        #pragma warning restore CS1591
        [EnumMember(Value = "WindAngle")]
        #pragma warning disable CS1591
        WindAngle,
        #pragma warning restore CS1591
        [EnumMember(Value = "Guststrength")]
        #pragma warning disable CS1591
        Guststrength,
        #pragma warning restore CS1591
        [EnumMember(Value = "GustAngle")]
        #pragma warning disable CS1591
        GustAngle,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sp_Temperature")]
        #pragma warning disable CS1591
        Sp_Temperature,
        #pragma warning restore CS1591
        [EnumMember(Value = "BoilerOn")]
        #pragma warning disable CS1591
        BoilerOn,
        #pragma warning restore CS1591
        [EnumMember(Value = "BoilerOff")]
        #pragma warning disable CS1591
        BoilerOff,
        #pragma warning restore CS1591
        [EnumMember(Value = "min_temp")]
        #pragma warning disable CS1591
        Min_temp,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_min_temp")]
        #pragma warning disable CS1591
        Date_min_temp,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_temp")]
        #pragma warning disable CS1591
        Max_temp,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_max_temp")]
        #pragma warning disable CS1591
        Date_max_temp,
        #pragma warning restore CS1591
        [EnumMember(Value = "min_hum")]
        #pragma warning disable CS1591
        Min_hum,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_min_hum")]
        #pragma warning disable CS1591
        Date_min_hum,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_hum")]
        #pragma warning disable CS1591
        Max_hum,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_max_hum")]
        #pragma warning disable CS1591
        Date_max_hum,
        #pragma warning restore CS1591
        [EnumMember(Value = "min_pressure")]
        #pragma warning disable CS1591
        Min_pressure,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_min_pressure")]
        #pragma warning disable CS1591
        Date_min_pressure,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_pressure")]
        #pragma warning disable CS1591
        Max_pressure,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_max_pressure")]
        #pragma warning disable CS1591
        Date_max_pressure,
        #pragma warning restore CS1591
        [EnumMember(Value = "min_noise")]
        #pragma warning disable CS1591
        Min_noise,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_min_noise")]
        #pragma warning disable CS1591
        Date_min_noise,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_noise")]
        #pragma warning disable CS1591
        Max_noise,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_max_noise")]
        #pragma warning disable CS1591
        Date_max_noise,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_min_co2")]
        #pragma warning disable CS1591
        Date_min_co2,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_max_co2")]
        #pragma warning disable CS1591
        Date_max_co2,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_max_gust")]
        #pragma warning disable CS1591
        Date_max_gust,
        #pragma warning restore CS1591
        [EnumMember(Value = "sum_rain")]
        #pragma warning disable CS1591
        Sum_rain,
        #pragma warning restore CS1591
        [EnumMember(Value = "sum_boiler_on")]
        #pragma warning disable CS1591
        Sum_boiler_on,
        #pragma warning restore CS1591
        [EnumMember(Value = "sum_boiler_off")]
        #pragma warning disable CS1591
        Sum_boiler_off,
        #pragma warning restore CS1591
    }
}
