// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Setpersonshome
{
    /// <summary>
    /// Builds and executes requests for operations under \setpersonshome
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SetpersonshomeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SetpersonshomeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setpersonshome?home_id={home_id}&person_ids={person_ids}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SetpersonshomeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setpersonshome?home_id={home_id}&person_ids={person_ids}", rawUrl)
        {
        }
        /// <summary>
        /// Sets a person as &apos;At home&apos;.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAWelcomePersonsHomeResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NAWelcomePersonsHomeResponse?> PostAsync(Action<RequestConfiguration<global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder.SetpersonshomeRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NAWelcomePersonsHomeResponse> PostAsync(Action<RequestConfiguration<global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder.SetpersonshomeRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NAWelcomePersonsHomeResponse>(requestInfo, global::NetatmoClient.Models.NAWelcomePersonsHomeResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Sets a person as &apos;At home&apos;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder.SetpersonshomeRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder.SetpersonshomeRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Setpersonshome.SetpersonshomeRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Sets a person as &apos;At home&apos;.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SetpersonshomeRequestBuilderPostQueryParameters 
        {
            /// <summary>ID of the Home you&apos;re interested in</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("home_id")]
            public string? HomeId { get; set; }
#nullable restore
#else
            [QueryParameter("home_id")]
            public string HomeId { get; set; }
#endif
            /// <summary>List of persons IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("person_ids")]
            public string? PersonIds { get; set; }
#nullable restore
#else
            [QueryParameter("person_ids")]
            public string PersonIds { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
