// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Devicelist
{
    /// <summary>
    /// Builds and executes requests for operations under \devicelist
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DevicelistRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Devicelist.DevicelistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DevicelistRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/devicelist{?app_type*,device_id*,get_favorites*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Devicelist.DevicelistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DevicelistRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/devicelist{?app_type*,device_id*,get_favorites*}", rawUrl)
        {
        }
        /// <summary>
        /// The method devicelist returns the list of devices owned by the user, and their modules.A device is identified by its _id (which is its mac address) and each device may have one, several or no modules, also identified by an _id.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NADeviceListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NADeviceListResponse?> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Devicelist.DevicelistRequestBuilder.DevicelistRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NADeviceListResponse> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Devicelist.DevicelistRequestBuilder.DevicelistRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NADeviceListResponse>(requestInfo, global::NetatmoClient.Models.NADeviceListResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The method devicelist returns the list of devices owned by the user, and their modules.A device is identified by its _id (which is its mac address) and each device may have one, several or no modules, also identified by an _id.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Devicelist.DevicelistRequestBuilder.DevicelistRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Devicelist.DevicelistRequestBuilder.DevicelistRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Devicelist.DevicelistRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::NetatmoClient.Devicelist.DevicelistRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Devicelist.DevicelistRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// The method devicelist returns the list of devices owned by the user, and their modules.A device is identified by its _id (which is its mac address) and each device may have one, several or no modules, also identified by an _id.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DevicelistRequestBuilderGetQueryParameters 
        {
            /// <summary>Defines which device type will be returned by devicelist. It could be app_thermostat or app_station (by default if not provided)</summary>
            [QueryParameter("app_type")]
            public global::NetatmoClient.Devicelist.GetApp_typeQueryParameterType? AppType { get; set; }
            /// <summary>Specify a device_id if you want to retrieve only this device informations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("device_id")]
            public string? DeviceId { get; set; }
#nullable restore
#else
            [QueryParameter("device_id")]
            public string DeviceId { get; set; }
#endif
            /// <summary>When set to &quot;true&quot;, the favorite devices of the user are returned. This flag is available only if the devices requested are Weather Stations.</summary>
            [QueryParameter("get_favorites")]
            public bool? GetFavorites { get; set; }
        }
    }
}
#pragma warning restore CS0618
