// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NetatmoClient.Devicelist
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetApp_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "app_thermostat")]
        #pragma warning disable CS1591
        App_thermostat,
        #pragma warning restore CS1591
        [EnumMember(Value = "app_station")]
        #pragma warning disable CS1591
        App_station,
        #pragma warning restore CS1591
    }
}
