// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Getpublicdata
{
    /// <summary>
    /// Builds and executes requests for operations under \getpublicdata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetpublicdataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetpublicdataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getpublicdata?lat_ne={lat_ne}&lat_sw={lat_sw}&lon_ne={lon_ne}&lon_sw={lon_sw}{&filter*,required_data*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetpublicdataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getpublicdata?lat_ne={lat_ne}&lat_sw={lat_sw}&lon_ne={lon_ne}&lon_sw={lon_sw}{&filter*,required_data*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves publicly shared weather data from Outdoor Modules within a predefined area.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAPublicDataResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NAPublicDataResponse?> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder.GetpublicdataRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NAPublicDataResponse> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder.GetpublicdataRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NAPublicDataResponse>(requestInfo, global::NetatmoClient.Models.NAPublicDataResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves publicly shared weather data from Outdoor Modules within a predefined area.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder.GetpublicdataRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder.GetpublicdataRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Getpublicdata.GetpublicdataRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves publicly shared weather data from Outdoor Modules within a predefined area.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetpublicdataRequestBuilderGetQueryParameters 
        {
            /// <summary>True to exclude stations with abnormal temperature measures. Default is false.</summary>
            [QueryParameter("filter")]
            public bool? Filter { get; set; }
            /// <summary>Latitude of the north east corner of the requested area. -85 &lt;= lat_ne &lt;= 85 and lat_ne&gt;lat_sw</summary>
            [QueryParameter("lat_ne")]
            public int? LatNe { get; set; }
            /// <summary>Latitude of the south west corner of the requested area. -85 &lt;= lat_sw &lt;= 85</summary>
            [QueryParameter("lat_sw")]
            public int? LatSw { get; set; }
            /// <summary>Longitude of the north east corner of the requested area. -180 &lt;= lon_ne &lt;= 180 and lon_ne&gt;lon_sw</summary>
            [QueryParameter("lon_ne")]
            public int? LonNe { get; set; }
            /// <summary>Longitude of the south west corner of the requested area. -180 &lt;= lon_sw &lt;= 180</summary>
            [QueryParameter("lon_sw")]
            public int? LonSw { get; set; }
            /// <summary>To filter stations based on relevant measurements you want (e.g. rain will only return stations with rain gauges). Default is no filter. You can find all measurements available on the Thermostat page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("required_data")]
            public global::NetatmoClient.Getpublicdata.GetRequired_dataQueryParameterType[]? RequiredData { get; set; }
#nullable restore
#else
            [QueryParameter("required_data")]
            public global::NetatmoClient.Getpublicdata.GetRequired_dataQueryParameterType[] RequiredData { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
