// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NetatmoClient.Getpublicdata
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetRequired_dataQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "temperature")]
        #pragma warning disable CS1591
        Temperature,
        #pragma warning restore CS1591
        [EnumMember(Value = "humidity")]
        #pragma warning disable CS1591
        Humidity,
        #pragma warning restore CS1591
        [EnumMember(Value = "pressure")]
        #pragma warning disable CS1591
        Pressure,
        #pragma warning restore CS1591
        [EnumMember(Value = "wind")]
        #pragma warning disable CS1591
        Wind,
        #pragma warning restore CS1591
        [EnumMember(Value = "rain")]
        #pragma warning disable CS1591
        Rain,
        #pragma warning restore CS1591
    }
}
