// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Createnewschedule
{
    /// <summary>
    /// Builds and executes requests for operations under \createnewschedule
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreatenewscheduleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreatenewscheduleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/createnewschedule?device_id={device_id}&module_id={module_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreatenewscheduleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/createnewschedule?device_id={device_id}&module_id={module_id}", rawUrl)
        {
        }
        /// <summary>
        /// The method createnewschedule creates a new schedule stored in the backup list.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NANewScheduleResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NANewScheduleResponse?> PostAsync(global::NetatmoClient.Models.NAThermProgram body, Action<RequestConfiguration<global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder.CreatenewscheduleRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NANewScheduleResponse> PostAsync(global::NetatmoClient.Models.NAThermProgram body, Action<RequestConfiguration<global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder.CreatenewscheduleRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NANewScheduleResponse>(requestInfo, global::NetatmoClient.Models.NANewScheduleResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The method createnewschedule creates a new schedule stored in the backup list.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::NetatmoClient.Models.NAThermProgram body, Action<RequestConfiguration<global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder.CreatenewscheduleRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::NetatmoClient.Models.NAThermProgram body, Action<RequestConfiguration<global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder.CreatenewscheduleRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "text/plain", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Createnewschedule.CreatenewscheduleRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// The method createnewschedule creates a new schedule stored in the backup list.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreatenewscheduleRequestBuilderPostQueryParameters 
        {
            /// <summary>The relay id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("device_id")]
            public string? DeviceId { get; set; }
#nullable restore
#else
            [QueryParameter("device_id")]
            public string DeviceId { get; set; }
#endif
            /// <summary>The thermostat id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("module_id")]
            public string? ModuleId { get; set; }
#nullable restore
#else
            [QueryParameter("module_id")]
            public string ModuleId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
