// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Gethomecoachsdata
{
    /// <summary>
    /// Builds and executes requests for operations under \gethomecoachsdata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GethomecoachsdataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GethomecoachsdataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gethomecoachsdata{?device_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GethomecoachsdataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gethomecoachsdata{?device_id*}", rawUrl)
        {
        }
        /// <summary>
        /// The method gethomecoachsdata Returns data from a user Healthy Home Coach Station (measures and device specific data).
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAHealthyHomeCoachDataResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NAHealthyHomeCoachDataResponse?> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder.GethomecoachsdataRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NAHealthyHomeCoachDataResponse> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder.GethomecoachsdataRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NAHealthyHomeCoachDataResponse>(requestInfo, global::NetatmoClient.Models.NAHealthyHomeCoachDataResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The method gethomecoachsdata Returns data from a user Healthy Home Coach Station (measures and device specific data).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder.GethomecoachsdataRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder.GethomecoachsdataRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Gethomecoachsdata.GethomecoachsdataRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// The method gethomecoachsdata Returns data from a user Healthy Home Coach Station (measures and device specific data).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GethomecoachsdataRequestBuilderGetQueryParameters 
        {
            /// <summary>Id of the device you want to retrieve information of</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("device_id")]
            public string? DeviceId { get; set; }
#nullable restore
#else
            [QueryParameter("device_id")]
            public string DeviceId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
