// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Getthermostatsdata
{
    /// <summary>
    /// Builds and executes requests for operations under \getthermostatsdata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetthermostatsdataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetthermostatsdataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getthermostatsdata{?device_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetthermostatsdataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getthermostatsdata{?device_id*}", rawUrl)
        {
        }
        /// <summary>
        /// The method getthermostatsdata returns information about user&apos;s thermostats such as their last measurements.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAThermostatDataResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NAThermostatDataResponse?> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder.GetthermostatsdataRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NAThermostatDataResponse> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder.GetthermostatsdataRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NAThermostatDataResponse>(requestInfo, global::NetatmoClient.Models.NAThermostatDataResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The method getthermostatsdata returns information about user&apos;s thermostats such as their last measurements.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder.GetthermostatsdataRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder.GetthermostatsdataRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Getthermostatsdata.GetthermostatsdataRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// The method getthermostatsdata returns information about user&apos;s thermostats such as their last measurements.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetthermostatsdataRequestBuilderGetQueryParameters 
        {
            /// <summary>Id of the device you want to retrieve information of</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("device_id")]
            public string? DeviceId { get; set; }
#nullable restore
#else
            [QueryParameter("device_id")]
            public string DeviceId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
