// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace NetatmoClient.Setthermpoint
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostSetpoint_modeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "program")]
        #pragma warning disable CS1591
        Program,
        #pragma warning restore CS1591
        [EnumMember(Value = "away")]
        #pragma warning disable CS1591
        Away,
        #pragma warning restore CS1591
        [EnumMember(Value = "hg")]
        #pragma warning disable CS1591
        Hg,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
        [EnumMember(Value = "max")]
        #pragma warning disable CS1591
        Max,
        #pragma warning restore CS1591
    }
}
