// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Setthermpoint
{
    /// <summary>
    /// Builds and executes requests for operations under \setthermpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SetthermpointRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SetthermpointRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setthermpoint?device_id={device_id}&module_id={module_id}&setpoint_mode={setpoint_mode}{&setpoint_endtime*,setpoint_temp*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SetthermpointRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setthermpoint?device_id={device_id}&module_id={module_id}&setpoint_mode={setpoint_mode}{&setpoint_endtime*,setpoint_temp*}", rawUrl)
        {
        }
        /// <summary>
        /// The method setthermpoint changes the Thermostat manual temperature setpoint.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAOkResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NAOkResponse?> PostAsync(Action<RequestConfiguration<global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder.SetthermpointRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NAOkResponse> PostAsync(Action<RequestConfiguration<global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder.SetthermpointRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NAOkResponse>(requestInfo, global::NetatmoClient.Models.NAOkResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The method setthermpoint changes the Thermostat manual temperature setpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder.SetthermpointRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder.SetthermpointRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Setthermpoint.SetthermpointRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// The method setthermpoint changes the Thermostat manual temperature setpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SetthermpointRequestBuilderPostQueryParameters 
        {
            /// <summary>The relay id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("device_id")]
            public string? DeviceId { get; set; }
#nullable restore
#else
            [QueryParameter("device_id")]
            public string DeviceId { get; set; }
#endif
            /// <summary>The thermostat id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("module_id")]
            public string? ModuleId { get; set; }
#nullable restore
#else
            [QueryParameter("module_id")]
            public string ModuleId { get; set; }
#endif
            /// <summary>When using the manual or max setpoint_mode, this parameter defines when the setpoint expires.</summary>
            [QueryParameter("setpoint_endtime")]
            public int? SetpointEndtime { get; set; }
            /// <summary>Chosen setpoint_mode</summary>
            [QueryParameter("setpoint_mode")]
            public global::NetatmoClient.Setthermpoint.PostSetpoint_modeQueryParameterType? SetpointMode { get; set; }
            /// <summary>When using the manual setpoint_mode, this parameter defines the temperature setpoint (in Celcius) to use.</summary>
            [QueryParameter("setpoint_temp")]
            public float? SetpointTemp { get; set; }
        }
    }
}
#pragma warning restore CS0618
