// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using NetatmoClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace NetatmoClient.Getlasteventof
{
    /// <summary>
    /// Builds and executes requests for operations under \getlasteventof
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetlasteventofRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetlasteventofRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getlasteventof?home_id={home_id}&person_id={person_id}{&offset*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetlasteventofRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/getlasteventof?home_id={home_id}&person_id={person_id}{&offset*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns most recent events.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAWelcomeEventResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::NetatmoClient.Models.NAWelcomeEventResponse?> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder.GetlasteventofRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::NetatmoClient.Models.NAWelcomeEventResponse> GetAsync(Action<RequestConfiguration<global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder.GetlasteventofRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::NetatmoClient.Models.NAWelcomeEventResponse>(requestInfo, global::NetatmoClient.Models.NAWelcomeEventResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns most recent events.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder.GetlasteventofRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder.GetlasteventofRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder WithUrl(string rawUrl)
        {
            return new global::NetatmoClient.Getlasteventof.GetlasteventofRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns most recent events.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetlasteventofRequestBuilderGetQueryParameters 
        {
            /// <summary>ID of the Home you&apos;re interested in</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("home_id")]
            public string? HomeId { get; set; }
#nullable restore
#else
            [QueryParameter("home_id")]
            public string HomeId { get; set; }
#endif
            /// <summary>Number of events to retrieve. Default is 30.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>Your request will retrieve all events of the given home until the most recent event of the given person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("person_id")]
            public string? PersonId { get; set; }
#nullable restore
#else
            [QueryParameter("person_id")]
            public string PersonId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
