// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NADashboardData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Real measured pressure @ time_utc (in mb)</summary>
        public float? AbsolutePressure { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The BoilerOff property</summary>
        public int? BoilerOff { get; set; }
        /// <summary>The BoilerOn property</summary>
        public int? BoilerOn { get; set; }
        /// <summary>Last Co2 measured @ time_utc (in ppm)</summary>
        public float? CO2 { get; set; }
        /// <summary>Timestamp when max temperature was measured</summary>
        public int? DateMaxTemp { get; set; }
        /// <summary>Timestamp when max wind strength was measured</summary>
        public int? DateMaxWindStr { get; set; }
        /// <summary>Timestamp when min temperature was measured</summary>
        public int? DateMinTemp { get; set; }
        /// <summary>The device_id property</summary>
        public float? DeviceId { get; set; }
        /// <summary>Direction of the last 5 min highest gust wind</summary>
        public int? GustAngle { get; set; }
        /// <summary>Speed of the last 5 min highest gust wind</summary>
        public int? GustStrength { get; set; }
        /// <summary>Current health index: 0 = Healthy, 1 = Fine, 2 = Fair, 3 = Poor, 4 = Unhealthy</summary>
        public int? HealthIdx { get; set; }
        /// <summary>Last humidity measured @ time_utc (in %)</summary>
        public float? Humidity { get; set; }
        /// <summary>Min temperature of the day (measured @ date_min_temp)</summary>
        public float? MaxTemp { get; set; }
        /// <summary>The max_wind_str property</summary>
        public int? MaxWindStr { get; set; }
        /// <summary>Max temperature of the day (measured @ date_max_temp)</summary>
        public float? MinTemp { get; set; }
        /// <summary>Last noise measured @ time_utc (in db)</summary>
        public float? Noise { get; set; }
        /// <summary>Last Sea level pressure measured @ time_utc (in mb)</summary>
        public float? Pressure { get; set; }
        /// <summary>Pressure evolution trend</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PressureTrend { get; set; }
#nullable restore
#else
        public string PressureTrend { get; set; }
#endif
        /// <summary>Last rain measured (in mm)</summary>
        public float? Rain { get; set; }
        /// <summary>Amount of rain in last hour</summary>
        public float? SumRain1 { get; set; }
        /// <summary>Amount of rain today</summary>
        public float? SumRain24 { get; set; }
        /// <summary>Last temperature measure @ time_utc (in °C)</summary>
        public float? Temperature { get; set; }
        /// <summary>Temperature evolution trend</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TempTrend { get; set; }
#nullable restore
#else
        public string TempTrend { get; set; }
#endif
        /// <summary>The time_utc property</summary>
        public int? TimeUtc { get; set; }
        /// <summary>Current 5 min average wind direction measured @ time_utc (in °)</summary>
        public int? WindAngle { get; set; }
        /// <summary>Current 5 min average wind speed measured @ time_utc (in km/h)</summary>
        public int? WindStrength { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NADashboardData"/> and sets the default values.
        /// </summary>
        public NADashboardData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NADashboardData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NADashboardData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NADashboardData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AbsolutePressure", n => { AbsolutePressure = n.GetFloatValue(); } },
                { "BoilerOff", n => { BoilerOff = n.GetIntValue(); } },
                { "BoilerOn", n => { BoilerOn = n.GetIntValue(); } },
                { "CO2", n => { CO2 = n.GetFloatValue(); } },
                { "date_max_temp", n => { DateMaxTemp = n.GetIntValue(); } },
                { "date_max_wind_str", n => { DateMaxWindStr = n.GetIntValue(); } },
                { "date_min_temp", n => { DateMinTemp = n.GetIntValue(); } },
                { "device_id", n => { DeviceId = n.GetFloatValue(); } },
                { "GustAngle", n => { GustAngle = n.GetIntValue(); } },
                { "GustStrength", n => { GustStrength = n.GetIntValue(); } },
                { "health_idx", n => { HealthIdx = n.GetIntValue(); } },
                { "Humidity", n => { Humidity = n.GetFloatValue(); } },
                { "max_temp", n => { MaxTemp = n.GetFloatValue(); } },
                { "max_wind_str", n => { MaxWindStr = n.GetIntValue(); } },
                { "min_temp", n => { MinTemp = n.GetFloatValue(); } },
                { "Noise", n => { Noise = n.GetFloatValue(); } },
                { "Pressure", n => { Pressure = n.GetFloatValue(); } },
                { "pressure_trend", n => { PressureTrend = n.GetStringValue(); } },
                { "Rain", n => { Rain = n.GetFloatValue(); } },
                { "sum_rain_1", n => { SumRain1 = n.GetFloatValue(); } },
                { "sum_rain_24", n => { SumRain24 = n.GetFloatValue(); } },
                { "temp_trend", n => { TempTrend = n.GetStringValue(); } },
                { "Temperature", n => { Temperature = n.GetFloatValue(); } },
                { "time_utc", n => { TimeUtc = n.GetIntValue(); } },
                { "WindAngle", n => { WindAngle = n.GetIntValue(); } },
                { "WindStrength", n => { WindStrength = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("AbsolutePressure", AbsolutePressure);
            writer.WriteIntValue("BoilerOff", BoilerOff);
            writer.WriteIntValue("BoilerOn", BoilerOn);
            writer.WriteFloatValue("CO2", CO2);
            writer.WriteIntValue("date_max_temp", DateMaxTemp);
            writer.WriteIntValue("date_max_wind_str", DateMaxWindStr);
            writer.WriteIntValue("date_min_temp", DateMinTemp);
            writer.WriteFloatValue("device_id", DeviceId);
            writer.WriteIntValue("GustAngle", GustAngle);
            writer.WriteIntValue("GustStrength", GustStrength);
            writer.WriteIntValue("health_idx", HealthIdx);
            writer.WriteFloatValue("Humidity", Humidity);
            writer.WriteFloatValue("max_temp", MaxTemp);
            writer.WriteIntValue("max_wind_str", MaxWindStr);
            writer.WriteFloatValue("min_temp", MinTemp);
            writer.WriteFloatValue("Noise", Noise);
            writer.WriteFloatValue("Pressure", Pressure);
            writer.WriteStringValue("pressure_trend", PressureTrend);
            writer.WriteFloatValue("Rain", Rain);
            writer.WriteFloatValue("sum_rain_1", SumRain1);
            writer.WriteFloatValue("sum_rain_24", SumRain24);
            writer.WriteFloatValue("Temperature", Temperature);
            writer.WriteStringValue("temp_trend", TempTrend);
            writer.WriteIntValue("time_utc", TimeUtc);
            writer.WriteIntValue("WindAngle", WindAngle);
            writer.WriteIntValue("WindStrength", WindStrength);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
