// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NADevice : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The behavior property</summary>
        public int? Behavior { get; set; }
        /// <summary>The cipher_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CipherId { get; set; }
#nullable restore
#else
        public string CipherId { get; set; }
#endif
        /// <summary>The dashboard_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADashboardData? DashboardData { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADashboardData DashboardData { get; set; }
#endif
        /// <summary>The data_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DataType { get; set; }
#nullable restore
#else
        public List<string> DataType { get; set; }
#endif
        /// <summary>The date_setup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADate? DateSetup { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADate DateSetup { get; set; }
#endif
        /// <summary>The firmware property</summary>
        public int? Firmware { get; set; }
        /// <summary>The first_pid_avail property</summary>
        public bool? FirstPidAvail { get; set; }
        /// <summary>The heating_system property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAHeatingSystem? HeatingSystem { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAHeatingSystem HeatingSystem { get; set; }
#endif
        /// <summary>The house_model property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAHouseModel? HouseModel { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAHouseModel HouseModel { get; set; }
#endif
        /// <summary>The hw_version property</summary>
        public int? HwVersion { get; set; }
        /// <summary>The _id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The ip property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ip { get; set; }
#nullable restore
#else
        public string Ip { get; set; }
#endif
        /// <summary>The last_fw_update property</summary>
        public int? LastFwUpdate { get; set; }
        /// <summary>The last_radio_store property</summary>
        public int? LastRadioStore { get; set; }
        /// <summary>The last_status_store property</summary>
        public int? LastStatusStore { get; set; }
        /// <summary>The last_upgrade property</summary>
        public int? LastUpgrade { get; set; }
        /// <summary>The module_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModuleName { get; set; }
#nullable restore
#else
        public string ModuleName { get; set; }
#endif
        /// <summary>It lists which modules are linked with this device</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Modules { get; set; }
#nullable restore
#else
        public List<string> Modules { get; set; }
#endif
        /// <summary>The new_feature_avail property</summary>
        public bool? NewFeatureAvail { get; set; }
        /// <summary>The place property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAPlace? Place { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAPlace Place { get; set; }
#endif
        /// <summary>The public_ext_data property</summary>
        public bool? PublicExtData { get; set; }
        /// <summary>The setpoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADevice_setpoint? Setpoint { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADevice_setpoint Setpoint { get; set; }
#endif
        /// <summary>The setpoint_default_duration property</summary>
        public int? SetpointDefaultDuration { get; set; }
        /// <summary>The setpoint_order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADevice_setpoint_order? SetpointOrder { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADevice_setpoint_order SetpointOrder { get; set; }
#endif
        /// <summary>The station_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationName { get; set; }
#nullable restore
#else
        public string StationName { get; set; }
#endif
        /// <summary>The therm_program property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADevice_therm_program? ThermProgram { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADevice_therm_program ThermProgram { get; set; }
#endif
        /// <summary>The therm_program_backup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADevice_therm_program_backup? ThermProgramBackup { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADevice_therm_program_backup ThermProgramBackup { get; set; }
#endif
        /// <summary>The therm_program_order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADevice_therm_program_order? ThermProgramOrder { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADevice_therm_program_order ThermProgramOrder { get; set; }
#endif
        /// <summary>Included in every device or module. It defines the type of the device/module. Its values are among :NAMain : for the base stationNAModule1 : for the outdoor moduleNAModule4 : for the additionnal indoor moduleNAModule3 : for the rain gauge moduleNAPlug : for the thermostat relay/plugNATherm1 : for the thermostat module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The udp_conn property</summary>
        public bool? UdpConn { get; set; }
        /// <summary>The user_owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? UserOwner { get; set; }
#nullable restore
#else
        public List<string> UserOwner { get; set; }
#endif
        /// <summary>It contains the current wifi status. The different thresholds to take into account areRSSI_THRESHOLD_0 = 86 bad signalRSSI_THRESHOLD_1 = 71 middle quality signalRSSI_THRESHOLD_2 = 56 good signal</summary>
        public int? WifiStatus { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NADevice"/> and sets the default values.
        /// </summary>
        public NADevice()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NADevice"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NADevice CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NADevice();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "behavior", n => { Behavior = n.GetIntValue(); } },
                { "cipher_id", n => { CipherId = n.GetStringValue(); } },
                { "dashboard_data", n => { DashboardData = n.GetObjectValue<global::NetatmoClient.Models.NADashboardData>(global::NetatmoClient.Models.NADashboardData.CreateFromDiscriminatorValue); } },
                { "data_type", n => { DataType = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "date_setup", n => { DateSetup = n.GetObjectValue<global::NetatmoClient.Models.NADate>(global::NetatmoClient.Models.NADate.CreateFromDiscriminatorValue); } },
                { "firmware", n => { Firmware = n.GetIntValue(); } },
                { "first_pid_avail", n => { FirstPidAvail = n.GetBoolValue(); } },
                { "heating_system", n => { HeatingSystem = n.GetObjectValue<global::NetatmoClient.Models.NAHeatingSystem>(global::NetatmoClient.Models.NAHeatingSystem.CreateFromDiscriminatorValue); } },
                { "house_model", n => { HouseModel = n.GetObjectValue<global::NetatmoClient.Models.NAHouseModel>(global::NetatmoClient.Models.NAHouseModel.CreateFromDiscriminatorValue); } },
                { "hw_version", n => { HwVersion = n.GetIntValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "ip", n => { Ip = n.GetStringValue(); } },
                { "last_fw_update", n => { LastFwUpdate = n.GetIntValue(); } },
                { "last_radio_store", n => { LastRadioStore = n.GetIntValue(); } },
                { "last_status_store", n => { LastStatusStore = n.GetIntValue(); } },
                { "last_upgrade", n => { LastUpgrade = n.GetIntValue(); } },
                { "module_name", n => { ModuleName = n.GetStringValue(); } },
                { "modules", n => { Modules = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "new_feature_avail", n => { NewFeatureAvail = n.GetBoolValue(); } },
                { "place", n => { Place = n.GetObjectValue<global::NetatmoClient.Models.NAPlace>(global::NetatmoClient.Models.NAPlace.CreateFromDiscriminatorValue); } },
                { "public_ext_data", n => { PublicExtData = n.GetBoolValue(); } },
                { "setpoint", n => { Setpoint = n.GetObjectValue<global::NetatmoClient.Models.NADevice_setpoint>(global::NetatmoClient.Models.NADevice_setpoint.CreateFromDiscriminatorValue); } },
                { "setpoint_default_duration", n => { SetpointDefaultDuration = n.GetIntValue(); } },
                { "setpoint_order", n => { SetpointOrder = n.GetObjectValue<global::NetatmoClient.Models.NADevice_setpoint_order>(global::NetatmoClient.Models.NADevice_setpoint_order.CreateFromDiscriminatorValue); } },
                { "station_name", n => { StationName = n.GetStringValue(); } },
                { "therm_program", n => { ThermProgram = n.GetObjectValue<global::NetatmoClient.Models.NADevice_therm_program>(global::NetatmoClient.Models.NADevice_therm_program.CreateFromDiscriminatorValue); } },
                { "therm_program_backup", n => { ThermProgramBackup = n.GetObjectValue<global::NetatmoClient.Models.NADevice_therm_program_backup>(global::NetatmoClient.Models.NADevice_therm_program_backup.CreateFromDiscriminatorValue); } },
                { "therm_program_order", n => { ThermProgramOrder = n.GetObjectValue<global::NetatmoClient.Models.NADevice_therm_program_order>(global::NetatmoClient.Models.NADevice_therm_program_order.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "udp_conn", n => { UdpConn = n.GetBoolValue(); } },
                { "user_owner", n => { UserOwner = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "wifi_status", n => { WifiStatus = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("behavior", Behavior);
            writer.WriteStringValue("cipher_id", CipherId);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADashboardData>("dashboard_data", DashboardData);
            writer.WriteCollectionOfPrimitiveValues<string>("data_type", DataType);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADate>("date_setup", DateSetup);
            writer.WriteIntValue("firmware", Firmware);
            writer.WriteBoolValue("first_pid_avail", FirstPidAvail);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAHeatingSystem>("heating_system", HeatingSystem);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAHouseModel>("house_model", HouseModel);
            writer.WriteIntValue("hw_version", HwVersion);
            writer.WriteStringValue("_id", Id);
            writer.WriteStringValue("ip", Ip);
            writer.WriteIntValue("last_fw_update", LastFwUpdate);
            writer.WriteIntValue("last_radio_store", LastRadioStore);
            writer.WriteIntValue("last_status_store", LastStatusStore);
            writer.WriteIntValue("last_upgrade", LastUpgrade);
            writer.WriteStringValue("module_name", ModuleName);
            writer.WriteCollectionOfPrimitiveValues<string>("modules", Modules);
            writer.WriteBoolValue("new_feature_avail", NewFeatureAvail);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAPlace>("place", Place);
            writer.WriteBoolValue("public_ext_data", PublicExtData);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADevice_setpoint>("setpoint", Setpoint);
            writer.WriteIntValue("setpoint_default_duration", SetpointDefaultDuration);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADevice_setpoint_order>("setpoint_order", SetpointOrder);
            writer.WriteStringValue("station_name", StationName);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADevice_therm_program>("therm_program", ThermProgram);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADevice_therm_program_backup>("therm_program_backup", ThermProgramBackup);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADevice_therm_program_order>("therm_program_order", ThermProgramOrder);
            writer.WriteStringValue("type", Type);
            writer.WriteBoolValue("udp_conn", UdpConn);
            writer.WriteCollectionOfPrimitiveValues<string>("user_owner", UserOwner);
            writer.WriteIntValue("wifi_status", WifiStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
