// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAHealthyHomeCoach : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cipher_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CipherId { get; set; }
#nullable restore
#else
        public string CipherId { get; set; }
#endif
        /// <summary>The co2_calibrating property</summary>
        public bool? Co2Calibrating { get; set; }
        /// <summary>The dashboard_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADashboardData? DashboardData { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADashboardData DashboardData { get; set; }
#endif
        /// <summary>The data_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DataType { get; set; }
#nullable restore
#else
        public List<string> DataType { get; set; }
#endif
        /// <summary>The date_setup property</summary>
        public int? DateSetup { get; set; }
        /// <summary>The firmware property</summary>
        public int? Firmware { get; set; }
        /// <summary>The _id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The last_setup property</summary>
        public int? LastSetup { get; set; }
        /// <summary>The last_status_store property</summary>
        public int? LastStatusStore { get; set; }
        /// <summary>The last_upgrade property</summary>
        public int? LastUpgrade { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The place property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAPlace? Place { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAPlace Place { get; set; }
#endif
        /// <summary>Included in every device or module. It defines the type of the device/module. Its values are among :NHC: Healthy Home Coach</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>It contains the current wifi status. The different thresholds to take into account areRSSI_THRESHOLD_0 = 86 bad signalRSSI_THRESHOLD_1 = 71 middle quality signalRSSI_THRESHOLD_2 = 56 good signal</summary>
        public int? WifiStatus { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAHealthyHomeCoach"/> and sets the default values.
        /// </summary>
        public NAHealthyHomeCoach()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAHealthyHomeCoach"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAHealthyHomeCoach CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAHealthyHomeCoach();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cipher_id", n => { CipherId = n.GetStringValue(); } },
                { "co2_calibrating", n => { Co2Calibrating = n.GetBoolValue(); } },
                { "dashboard_data", n => { DashboardData = n.GetObjectValue<global::NetatmoClient.Models.NADashboardData>(global::NetatmoClient.Models.NADashboardData.CreateFromDiscriminatorValue); } },
                { "data_type", n => { DataType = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "date_setup", n => { DateSetup = n.GetIntValue(); } },
                { "firmware", n => { Firmware = n.GetIntValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "last_setup", n => { LastSetup = n.GetIntValue(); } },
                { "last_status_store", n => { LastStatusStore = n.GetIntValue(); } },
                { "last_upgrade", n => { LastUpgrade = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "place", n => { Place = n.GetObjectValue<global::NetatmoClient.Models.NAPlace>(global::NetatmoClient.Models.NAPlace.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "wifi_status", n => { WifiStatus = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cipher_id", CipherId);
            writer.WriteBoolValue("co2_calibrating", Co2Calibrating);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADashboardData>("dashboard_data", DashboardData);
            writer.WriteCollectionOfPrimitiveValues<string>("data_type", DataType);
            writer.WriteIntValue("date_setup", DateSetup);
            writer.WriteIntValue("firmware", Firmware);
            writer.WriteStringValue("_id", Id);
            writer.WriteIntValue("last_setup", LastSetup);
            writer.WriteIntValue("last_status_store", LastStatusStore);
            writer.WriteIntValue("last_upgrade", LastUpgrade);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAPlace>("place", Place);
            writer.WriteStringValue("type", Type);
            writer.WriteIntValue("wifi_status", WifiStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
