// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAHouseModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The algo_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlgoType { get; set; }
#nullable restore
#else
        public string AlgoType { get; set; }
#endif
        /// <summary>The ca property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAHouseModelCa? Ca { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAHouseModelCa Ca { get; set; }
#endif
        /// <summary>The ext_temps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAHouseModel_ext_temps? ExtTemps { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAHouseModel_ext_temps ExtTemps { get; set; }
#endif
        /// <summary>The first_anticipate_avail property</summary>
        public bool? FirstAnticipateAvail { get; set; }
        /// <summary>The first_pid_avail property</summary>
        public bool? FirstPidAvail { get; set; }
        /// <summary>The gefs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAStation? Gefs { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAStation Gefs { get; set; }
#endif
        /// <summary>The in_use property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InUse { get; set; }
#nullable restore
#else
        public string InUse { get; set; }
#endif
        /// <summary>The last_compute_try property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADate? LastComputeTry { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADate LastComputeTry { get; set; }
#endif
        /// <summary>The link_station property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NALinkStation? LinkStation { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NALinkStation LinkStation { get; set; }
#endif
        /// <summary>The pid_algo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAPidAlgo? PidAlgo { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAPidAlgo PidAlgo { get; set; }
#endif
        /// <summary>The prefered_algo_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferedAlgoType { get; set; }
#nullable restore
#else
        public string PreferedAlgoType { get; set; }
#endif
        /// <summary>The simple_algo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NASimpleAlgo? SimpleAlgo { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NASimpleAlgo SimpleAlgo { get; set; }
#endif
        /// <summary>The station property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAStation? Station { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAStation Station { get; set; }
#endif
        /// <summary>The station_firsttime_anticipate property</summary>
        public bool? StationFirsttimeAnticipate { get; set; }
        /// <summary>The time property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADate? Time { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADate Time { get; set; }
#endif
        /// <summary>The time_algo_changed property</summary>
        public int? TimeAlgoChanged { get; set; }
        /// <summary>The time_pid_computed property</summary>
        public int? TimePidComputed { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAHouseModel"/> and sets the default values.
        /// </summary>
        public NAHouseModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAHouseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAHouseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAHouseModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "algo_type", n => { AlgoType = n.GetStringValue(); } },
                { "ca", n => { Ca = n.GetObjectValue<global::NetatmoClient.Models.NAHouseModelCa>(global::NetatmoClient.Models.NAHouseModelCa.CreateFromDiscriminatorValue); } },
                { "ext_temps", n => { ExtTemps = n.GetObjectValue<global::NetatmoClient.Models.NAHouseModel_ext_temps>(global::NetatmoClient.Models.NAHouseModel_ext_temps.CreateFromDiscriminatorValue); } },
                { "first_anticipate_avail", n => { FirstAnticipateAvail = n.GetBoolValue(); } },
                { "first_pid_avail", n => { FirstPidAvail = n.GetBoolValue(); } },
                { "gefs", n => { Gefs = n.GetObjectValue<global::NetatmoClient.Models.NAStation>(global::NetatmoClient.Models.NAStation.CreateFromDiscriminatorValue); } },
                { "in_use", n => { InUse = n.GetStringValue(); } },
                { "last_compute_try", n => { LastComputeTry = n.GetObjectValue<global::NetatmoClient.Models.NADate>(global::NetatmoClient.Models.NADate.CreateFromDiscriminatorValue); } },
                { "link_station", n => { LinkStation = n.GetObjectValue<global::NetatmoClient.Models.NALinkStation>(global::NetatmoClient.Models.NALinkStation.CreateFromDiscriminatorValue); } },
                { "pid_algo", n => { PidAlgo = n.GetObjectValue<global::NetatmoClient.Models.NAPidAlgo>(global::NetatmoClient.Models.NAPidAlgo.CreateFromDiscriminatorValue); } },
                { "prefered_algo_type", n => { PreferedAlgoType = n.GetStringValue(); } },
                { "simple_algo", n => { SimpleAlgo = n.GetObjectValue<global::NetatmoClient.Models.NASimpleAlgo>(global::NetatmoClient.Models.NASimpleAlgo.CreateFromDiscriminatorValue); } },
                { "station", n => { Station = n.GetObjectValue<global::NetatmoClient.Models.NAStation>(global::NetatmoClient.Models.NAStation.CreateFromDiscriminatorValue); } },
                { "station_firsttime_anticipate", n => { StationFirsttimeAnticipate = n.GetBoolValue(); } },
                { "time", n => { Time = n.GetObjectValue<global::NetatmoClient.Models.NADate>(global::NetatmoClient.Models.NADate.CreateFromDiscriminatorValue); } },
                { "time_algo_changed", n => { TimeAlgoChanged = n.GetIntValue(); } },
                { "time_pid_computed", n => { TimePidComputed = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("algo_type", AlgoType);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAHouseModelCa>("ca", Ca);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAHouseModel_ext_temps>("ext_temps", ExtTemps);
            writer.WriteBoolValue("first_anticipate_avail", FirstAnticipateAvail);
            writer.WriteBoolValue("first_pid_avail", FirstPidAvail);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAStation>("gefs", Gefs);
            writer.WriteStringValue("in_use", InUse);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADate>("last_compute_try", LastComputeTry);
            writer.WriteObjectValue<global::NetatmoClient.Models.NALinkStation>("link_station", LinkStation);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAPidAlgo>("pid_algo", PidAlgo);
            writer.WriteStringValue("prefered_algo_type", PreferedAlgoType);
            writer.WriteObjectValue<global::NetatmoClient.Models.NASimpleAlgo>("simple_algo", SimpleAlgo);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAStation>("station", Station);
            writer.WriteBoolValue("station_firsttime_anticipate", StationFirsttimeAnticipate);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADate>("time", Time);
            writer.WriteIntValue("time_algo_changed", TimeAlgoChanged);
            writer.WriteIntValue("time_pid_computed", TimePidComputed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
