// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAPlug : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The firmware property</summary>
        public int? Firmware { get; set; }
        /// <summary>The _id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The last_bilan property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAYearMonth? LastBilan { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAYearMonth LastBilan { get; set; }
#endif
        /// <summary>The last_plug_seen property</summary>
        public int? LastPlugSeen { get; set; }
        /// <summary>The last_status_store property</summary>
        public int? LastStatusStore { get; set; }
        /// <summary>The modules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NAThermostat>? Modules { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NAThermostat> Modules { get; set; }
#endif
        /// <summary>The place property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAPlace? Place { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAPlace Place { get; set; }
#endif
        /// <summary>The plug_connected_boiler property</summary>
        public int? PlugConnectedBoiler { get; set; }
        /// <summary>The station_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StationName { get; set; }
#nullable restore
#else
        public string StationName { get; set; }
#endif
        /// <summary>The syncing property</summary>
        public bool? Syncing { get; set; }
        /// <summary>Included in every device or module. It defines the type of the device/module. Its values are among :NAMain : for the base stationNAModule1 : for the outdoor moduleNAModule4 : for the additionnal indoor moduleNAModule3 : for the rain gauge moduleNAPlug : for the thermostat relay/plugNATherm1 : for the thermostat module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The udp_conn property</summary>
        public bool? UdpConn { get; set; }
        /// <summary>It contains the current wifi status. The different thresholds to take into account areRSSI_THRESHOLD_0 = 86 bad signalRSSI_THRESHOLD_1 = 71 middle quality signalRSSI_THRESHOLD_2 = 56 good signal</summary>
        public int? WifiStatus { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAPlug"/> and sets the default values.
        /// </summary>
        public NAPlug()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAPlug"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAPlug CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAPlug();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "firmware", n => { Firmware = n.GetIntValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "last_bilan", n => { LastBilan = n.GetObjectValue<global::NetatmoClient.Models.NAYearMonth>(global::NetatmoClient.Models.NAYearMonth.CreateFromDiscriminatorValue); } },
                { "last_plug_seen", n => { LastPlugSeen = n.GetIntValue(); } },
                { "last_status_store", n => { LastStatusStore = n.GetIntValue(); } },
                { "modules", n => { Modules = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NAThermostat>(global::NetatmoClient.Models.NAThermostat.CreateFromDiscriminatorValue)?.AsList(); } },
                { "place", n => { Place = n.GetObjectValue<global::NetatmoClient.Models.NAPlace>(global::NetatmoClient.Models.NAPlace.CreateFromDiscriminatorValue); } },
                { "plug_connected_boiler", n => { PlugConnectedBoiler = n.GetIntValue(); } },
                { "station_name", n => { StationName = n.GetStringValue(); } },
                { "syncing", n => { Syncing = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "udp_conn", n => { UdpConn = n.GetBoolValue(); } },
                { "wifi_status", n => { WifiStatus = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("firmware", Firmware);
            writer.WriteStringValue("_id", Id);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAYearMonth>("last_bilan", LastBilan);
            writer.WriteIntValue("last_plug_seen", LastPlugSeen);
            writer.WriteIntValue("last_status_store", LastStatusStore);
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NAThermostat>("modules", Modules);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAPlace>("place", Place);
            writer.WriteIntValue("plug_connected_boiler", PlugConnectedBoiler);
            writer.WriteStringValue("station_name", StationName);
            writer.WriteBoolValue("syncing", Syncing);
            writer.WriteStringValue("type", Type);
            writer.WriteBoolValue("udp_conn", UdpConn);
            writer.WriteIntValue("wifi_status", WifiStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
