// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAPublicData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>id of the station</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The mark property</summary>
        public int? Mark { get; set; }
        /// <summary>The measures property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAPublicData_measures? Measures { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAPublicData_measures Measures { get; set; }
#endif
        /// <summary>The modules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Modules { get; set; }
#nullable restore
#else
        public List<string> Modules { get; set; }
#endif
        /// <summary>Latest measurements of the station, organized by module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAPublicData_module_types? ModuleTypes { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAPublicData_module_types ModuleTypes { get; set; }
#endif
        /// <summary>The place property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAPlace? Place { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAPlace Place { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAPublicData"/> and sets the default values.
        /// </summary>
        public NAPublicData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAPublicData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAPublicData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAPublicData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_id", n => { Id = n.GetStringValue(); } },
                { "mark", n => { Mark = n.GetIntValue(); } },
                { "measures", n => { Measures = n.GetObjectValue<global::NetatmoClient.Models.NAPublicData_measures>(global::NetatmoClient.Models.NAPublicData_measures.CreateFromDiscriminatorValue); } },
                { "module_types", n => { ModuleTypes = n.GetObjectValue<global::NetatmoClient.Models.NAPublicData_module_types>(global::NetatmoClient.Models.NAPublicData_module_types.CreateFromDiscriminatorValue); } },
                { "modules", n => { Modules = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "place", n => { Place = n.GetObjectValue<global::NetatmoClient.Models.NAPlace>(global::NetatmoClient.Models.NAPlace.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("_id", Id);
            writer.WriteIntValue("mark", Mark);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAPublicData_measures>("measures", Measures);
            writer.WriteCollectionOfPrimitiveValues<string>("modules", Modules);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAPublicData_module_types>("module_types", ModuleTypes);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAPlace>("place", Place);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
