// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAStationModule : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>It contains the current battery level in percentage.</summary>
        public int? BatteryPercent { get; set; }
        /// <summary>It contains the current battery status. The threshold depends on the kind of module, below is the list of the different threshold to take into account according the module type.&quot;Indoor module Battery range: 6000 ... 4200&quot; |INDOOR_BATTERY_LEVEL_FULL = 5640INDOOR_BATTERY_LEVEL_HIGH = 5280INDOOR_BATTERY_LEVEL_MEDIUM = 4920INDOOR_BATTERY_LEVEL_LOW = 4560&quot;Below 4560: very low&quot; |    &quot;Raingauge and outdoor module Battery range: 6000 ... 3600&quot; |BATTERY_LEVEL_FULL = 5500BATTERY_LEVEL_HIGH = 5000BATTERY_LEVEL_MEDIUM = 4500BATTERY_LEVEL_LOW = 4000&quot;Below 4000: very low&quot; |    &quot;Thermostat Battery range: 4500 ... 3000&quot; |THERMOSTAT_BATTERY_LEVEL_FULL = 4100THERMOSTAT_BATTERY_LEVEL_HIGH = 3600THERMOSTAT_BATTERY_LEVEL_MEDIUM = 3300THERMOSTAT_BATTERY_LEVEL_LOW = 3000&quot;Below 3000: very low&quot;</summary>
        public int? BatteryVp { get; set; }
        /// <summary>The dashboard_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADashboardData? DashboardData { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADashboardData DashboardData { get; set; }
#endif
        /// <summary>The data_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DataType { get; set; }
#nullable restore
#else
        public List<string> DataType { get; set; }
#endif
        /// <summary>The firmware property</summary>
        public int? Firmware { get; set; }
        /// <summary>The _id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The last_message property</summary>
        public int? LastMessage { get; set; }
        /// <summary>The last_seen property</summary>
        public int? LastSeen { get; set; }
        /// <summary>The last_setup property</summary>
        public int? LastSetup { get; set; }
        /// <summary>The module_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModuleName { get; set; }
#nullable restore
#else
        public string ModuleName { get; set; }
#endif
        /// <summary>&quot;It contains the current radio status. The different thresholds to take into account are :&quot; |RADIO_THRESHOLD_SIGNAL_LOW = 90 RADIO_THRESHOLD_SIGNAL_MEDIUM = 80RADIO_THRESHOLD_SIGNAL_HIGH = 70RADIO_THRESHOLD_SIGNAL_FULL = 60</summary>
        public int? RfStatus { get; set; }
        /// <summary>Included in every device or module. It defines the type of the device/module. Its values are among :NAMain : for the base stationNAModule1 : for the outdoor moduleNAModule4 : for the additionnal indoor moduleNAModule3 : for the rain gauge moduleNAPlug : for the thermostat relay/plugNATherm1 : for the thermostat module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAStationModule"/> and sets the default values.
        /// </summary>
        public NAStationModule()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAStationModule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAStationModule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAStationModule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "battery_percent", n => { BatteryPercent = n.GetIntValue(); } },
                { "battery_vp", n => { BatteryVp = n.GetIntValue(); } },
                { "dashboard_data", n => { DashboardData = n.GetObjectValue<global::NetatmoClient.Models.NADashboardData>(global::NetatmoClient.Models.NADashboardData.CreateFromDiscriminatorValue); } },
                { "data_type", n => { DataType = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "firmware", n => { Firmware = n.GetIntValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "last_message", n => { LastMessage = n.GetIntValue(); } },
                { "last_seen", n => { LastSeen = n.GetIntValue(); } },
                { "last_setup", n => { LastSetup = n.GetIntValue(); } },
                { "module_name", n => { ModuleName = n.GetStringValue(); } },
                { "rf_status", n => { RfStatus = n.GetIntValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("battery_percent", BatteryPercent);
            writer.WriteIntValue("battery_vp", BatteryVp);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADashboardData>("dashboard_data", DashboardData);
            writer.WriteCollectionOfPrimitiveValues<string>("data_type", DataType);
            writer.WriteIntValue("firmware", Firmware);
            writer.WriteStringValue("_id", Id);
            writer.WriteIntValue("last_message", LastMessage);
            writer.WriteIntValue("last_seen", LastSeen);
            writer.WriteIntValue("last_setup", LastSetup);
            writer.WriteStringValue("module_name", ModuleName);
            writer.WriteIntValue("rf_status", RfStatus);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
