// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAStation : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The lag_down property</summary>
        public int? LagDown { get; set; }
        /// <summary>The lag_up property</summary>
        public int? LagUp { get; set; }
        /// <summary>The off_overshoot property</summary>
        public float? OffOvershoot { get; set; }
        /// <summary>The on_overshoot property</summary>
        public float? OnOvershoot { get; set; }
        /// <summary>The pk property</summary>
        public int? Pk { get; set; }
        /// <summary>The tau property</summary>
        public int? Tau { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAStation"/> and sets the default values.
        /// </summary>
        public NAStation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAStation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAStation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAStation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lag_down", n => { LagDown = n.GetIntValue(); } },
                { "lag_up", n => { LagUp = n.GetIntValue(); } },
                { "off_overshoot", n => { OffOvershoot = n.GetFloatValue(); } },
                { "on_overshoot", n => { OnOvershoot = n.GetFloatValue(); } },
                { "pk", n => { Pk = n.GetIntValue(); } },
                { "tau", n => { Tau = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("lag_down", LagDown);
            writer.WriteIntValue("lag_up", LagUp);
            writer.WriteFloatValue("off_overshoot", OffOvershoot);
            writer.WriteFloatValue("on_overshoot", OnOvershoot);
            writer.WriteIntValue("pk", Pk);
            writer.WriteIntValue("tau", Tau);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
