// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAThermostat : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>It contains the current battery level in percentage.</summary>
        public int? BatteryPercent { get; set; }
        /// <summary>It contains the current battery status. The threshold depends on the kind of module, below is the list of the different threshold to take into account according the module type.&quot;Indoor module Battery range: 6000 ... 4200&quot; |INDOOR_BATTERY_LEVEL_FULL = 5640INDOOR_BATTERY_LEVEL_HIGH = 5280INDOOR_BATTERY_LEVEL_MEDIUM = 4920INDOOR_BATTERY_LEVEL_LOW = 4560&quot;Below 4560: very low&quot; |    &quot;Raingauge and outdoor module Battery range: 6000 ... 3600&quot; |BATTERY_LEVEL_FULL = 5500BATTERY_LEVEL_HIGH = 5000BATTERY_LEVEL_MEDIUM = 4500BATTERY_LEVEL_LOW = 4000&quot;Below 4000: very low&quot; |    &quot;Thermostat Battery range: 4500 ... 3000&quot; |THERMOSTAT_BATTERY_LEVEL_FULL = 4100THERMOSTAT_BATTERY_LEVEL_HIGH = 3600THERMOSTAT_BATTERY_LEVEL_MEDIUM = 3300THERMOSTAT_BATTERY_LEVEL_LOW = 3000&quot;Below 3000: very low&quot;</summary>
        public int? BatteryVp { get; set; }
        /// <summary>The firmware property</summary>
        public int? Firmware { get; set; }
        /// <summary>The _id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The last_message property</summary>
        public int? LastMessage { get; set; }
        /// <summary>The last_therm_seen property</summary>
        public int? LastThermSeen { get; set; }
        /// <summary>The measured property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAThermMeasure? Measured { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAThermMeasure Measured { get; set; }
#endif
        /// <summary>The module_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModuleName { get; set; }
#nullable restore
#else
        public string ModuleName { get; set; }
#endif
        /// <summary>&quot;It contains the current radio status. The different thresholds to take into account are :&quot; |RADIO_THRESHOLD_SIGNAL_LOW = 90 RADIO_THRESHOLD_SIGNAL_MEDIUM = 80RADIO_THRESHOLD_SIGNAL_HIGH = 70RADIO_THRESHOLD_SIGNAL_FULL = 60</summary>
        public int? RfStatus { get; set; }
        /// <summary>The setpoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NASetpoint? Setpoint { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NASetpoint Setpoint { get; set; }
#endif
        /// <summary>The last 20 setpoints (mode, endtime, and timestamp) the thermostats has entered.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NASetpointLog>? SetpointHistory { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NASetpointLog> SetpointHistory { get; set; }
#endif
        /// <summary>The setpoint_order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NASetpoint? SetpointOrder { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NASetpoint SetpointOrder { get; set; }
#endif
        /// <summary>The therm_orientation property</summary>
        public int? ThermOrientation { get; set; }
        /// <summary>List of the weekly heating planning used by the thermostat</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NAThermProgram>? ThermProgramList { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NAThermProgram> ThermProgramList { get; set; }
#endif
        /// <summary>The therm_relay_cmd property</summary>
        public int? ThermRelayCmd { get; set; }
        /// <summary>Included in every device or module. It defines the type of the device/module. Its values are among :NAMain : for the base stationNAModule1 : for the outdoor moduleNAModule4 : for the additionnal indoor moduleNAModule3 : for the rain gauge moduleNAPlug : for the thermostat relay/plugNATherm1 : for the thermostat module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAThermostat"/> and sets the default values.
        /// </summary>
        public NAThermostat()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAThermostat"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAThermostat CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAThermostat();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "battery_percent", n => { BatteryPercent = n.GetIntValue(); } },
                { "battery_vp", n => { BatteryVp = n.GetIntValue(); } },
                { "firmware", n => { Firmware = n.GetIntValue(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "last_message", n => { LastMessage = n.GetIntValue(); } },
                { "last_therm_seen", n => { LastThermSeen = n.GetIntValue(); } },
                { "measured", n => { Measured = n.GetObjectValue<global::NetatmoClient.Models.NAThermMeasure>(global::NetatmoClient.Models.NAThermMeasure.CreateFromDiscriminatorValue); } },
                { "module_name", n => { ModuleName = n.GetStringValue(); } },
                { "rf_status", n => { RfStatus = n.GetIntValue(); } },
                { "setpoint", n => { Setpoint = n.GetObjectValue<global::NetatmoClient.Models.NASetpoint>(global::NetatmoClient.Models.NASetpoint.CreateFromDiscriminatorValue); } },
                { "setpoint_history", n => { SetpointHistory = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NASetpointLog>(global::NetatmoClient.Models.NASetpointLog.CreateFromDiscriminatorValue)?.AsList(); } },
                { "setpoint_order", n => { SetpointOrder = n.GetObjectValue<global::NetatmoClient.Models.NASetpoint>(global::NetatmoClient.Models.NASetpoint.CreateFromDiscriminatorValue); } },
                { "therm_orientation", n => { ThermOrientation = n.GetIntValue(); } },
                { "therm_program_list", n => { ThermProgramList = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NAThermProgram>(global::NetatmoClient.Models.NAThermProgram.CreateFromDiscriminatorValue)?.AsList(); } },
                { "therm_relay_cmd", n => { ThermRelayCmd = n.GetIntValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("battery_percent", BatteryPercent);
            writer.WriteIntValue("battery_vp", BatteryVp);
            writer.WriteIntValue("firmware", Firmware);
            writer.WriteStringValue("_id", Id);
            writer.WriteIntValue("last_message", LastMessage);
            writer.WriteIntValue("last_therm_seen", LastThermSeen);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAThermMeasure>("measured", Measured);
            writer.WriteStringValue("module_name", ModuleName);
            writer.WriteIntValue("rf_status", RfStatus);
            writer.WriteObjectValue<global::NetatmoClient.Models.NASetpoint>("setpoint", Setpoint);
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NASetpointLog>("setpoint_history", SetpointHistory);
            writer.WriteObjectValue<global::NetatmoClient.Models.NASetpoint>("setpoint_order", SetpointOrder);
            writer.WriteIntValue("therm_orientation", ThermOrientation);
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NAThermProgram>("therm_program_list", ThermProgramList);
            writer.WriteIntValue("therm_relay_cmd", ThermRelayCmd);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
