// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAThermStateBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>It contains the current battery level in percentage.</summary>
        public int? BatteryPercent { get; set; }
        /// <summary>The battery_vp property</summary>
        public int? BatteryVp { get; set; }
        /// <summary>The last_plug_seen property</summary>
        public int? LastPlugSeen { get; set; }
        /// <summary>The last_therm_seen property</summary>
        public int? LastThermSeen { get; set; }
        /// <summary>The measured property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAThermMeasure? Measured { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAThermMeasure Measured { get; set; }
#endif
        /// <summary>The plug_connected_boiler property</summary>
        public int? PlugConnectedBoiler { get; set; }
        /// <summary>The rf_status property</summary>
        public int? RfStatus { get; set; }
        /// <summary>The setpoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NASetpoint? Setpoint { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NASetpoint Setpoint { get; set; }
#endif
        /// <summary>The setpoint_order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NASetpoint? SetpointOrder { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NASetpoint SetpointOrder { get; set; }
#endif
        /// <summary>The therm_orientation property</summary>
        public int? ThermOrientation { get; set; }
        /// <summary>The therm_program property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAThermProgram? ThermProgram { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAThermProgram ThermProgram { get; set; }
#endif
        /// <summary>The therm_program_backup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NAThermProgram>? ThermProgramBackup { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NAThermProgram> ThermProgramBackup { get; set; }
#endif
        /// <summary>The therm_program_order property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAThermProgram? ThermProgramOrder { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAThermProgram ThermProgramOrder { get; set; }
#endif
        /// <summary>The therm_relay_cmd property</summary>
        public int? ThermRelayCmd { get; set; }
        /// <summary>The udp_conn property</summary>
        public bool? UdpConn { get; set; }
        /// <summary>The wifi_status property</summary>
        public int? WifiStatus { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAThermStateBody"/> and sets the default values.
        /// </summary>
        public NAThermStateBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAThermStateBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAThermStateBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAThermStateBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "battery_percent", n => { BatteryPercent = n.GetIntValue(); } },
                { "battery_vp", n => { BatteryVp = n.GetIntValue(); } },
                { "last_plug_seen", n => { LastPlugSeen = n.GetIntValue(); } },
                { "last_therm_seen", n => { LastThermSeen = n.GetIntValue(); } },
                { "measured", n => { Measured = n.GetObjectValue<global::NetatmoClient.Models.NAThermMeasure>(global::NetatmoClient.Models.NAThermMeasure.CreateFromDiscriminatorValue); } },
                { "plug_connected_boiler", n => { PlugConnectedBoiler = n.GetIntValue(); } },
                { "rf_status", n => { RfStatus = n.GetIntValue(); } },
                { "setpoint", n => { Setpoint = n.GetObjectValue<global::NetatmoClient.Models.NASetpoint>(global::NetatmoClient.Models.NASetpoint.CreateFromDiscriminatorValue); } },
                { "setpoint_order", n => { SetpointOrder = n.GetObjectValue<global::NetatmoClient.Models.NASetpoint>(global::NetatmoClient.Models.NASetpoint.CreateFromDiscriminatorValue); } },
                { "therm_orientation", n => { ThermOrientation = n.GetIntValue(); } },
                { "therm_program", n => { ThermProgram = n.GetObjectValue<global::NetatmoClient.Models.NAThermProgram>(global::NetatmoClient.Models.NAThermProgram.CreateFromDiscriminatorValue); } },
                { "therm_program_backup", n => { ThermProgramBackup = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NAThermProgram>(global::NetatmoClient.Models.NAThermProgram.CreateFromDiscriminatorValue)?.AsList(); } },
                { "therm_program_order", n => { ThermProgramOrder = n.GetObjectValue<global::NetatmoClient.Models.NAThermProgram>(global::NetatmoClient.Models.NAThermProgram.CreateFromDiscriminatorValue); } },
                { "therm_relay_cmd", n => { ThermRelayCmd = n.GetIntValue(); } },
                { "udp_conn", n => { UdpConn = n.GetBoolValue(); } },
                { "wifi_status", n => { WifiStatus = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("battery_percent", BatteryPercent);
            writer.WriteIntValue("battery_vp", BatteryVp);
            writer.WriteIntValue("last_plug_seen", LastPlugSeen);
            writer.WriteIntValue("last_therm_seen", LastThermSeen);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAThermMeasure>("measured", Measured);
            writer.WriteIntValue("plug_connected_boiler", PlugConnectedBoiler);
            writer.WriteIntValue("rf_status", RfStatus);
            writer.WriteObjectValue<global::NetatmoClient.Models.NASetpoint>("setpoint", Setpoint);
            writer.WriteObjectValue<global::NetatmoClient.Models.NASetpoint>("setpoint_order", SetpointOrder);
            writer.WriteIntValue("therm_orientation", ThermOrientation);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAThermProgram>("therm_program", ThermProgram);
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NAThermProgram>("therm_program_backup", ThermProgramBackup);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAThermProgram>("therm_program_order", ThermProgramOrder);
            writer.WriteIntValue("therm_relay_cmd", ThermRelayCmd);
            writer.WriteBoolValue("udp_conn", UdpConn);
            writer.WriteIntValue("wifi_status", WifiStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
