// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAUser : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The administrative property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAUserAdministrative? Administrative { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAUserAdministrative Administrative { get; set; }
#endif
        /// <summary>The date_creation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NADate? DateCreation { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NADate DateCreation { get; set; }
#endif
        /// <summary>An array of string containing the ids of the devices owned by the user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Devices { get; set; }
#nullable restore
#else
        public List<string> Devices { get; set; }
#endif
        /// <summary>An array of string containing the ids of the devices on which the user has a &quot;guest&quot; access</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FriendDevices { get; set; }
#nullable restore
#else
        public List<string> FriendDevices { get; set; }
#endif
        /// <summary>The _id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The mail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mail { get; set; }
#nullable restore
#else
        public string Mail { get; set; }
#endif
        /// <summary>The timeline_not_read property</summary>
        public int? TimelineNotRead { get; set; }
        /// <summary>The timeline_size property</summary>
        public int? TimelineSize { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAUser"/> and sets the default values.
        /// </summary>
        public NAUser()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAUser"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAUser CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAUser();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "administrative", n => { Administrative = n.GetObjectValue<global::NetatmoClient.Models.NAUserAdministrative>(global::NetatmoClient.Models.NAUserAdministrative.CreateFromDiscriminatorValue); } },
                { "date_creation", n => { DateCreation = n.GetObjectValue<global::NetatmoClient.Models.NADate>(global::NetatmoClient.Models.NADate.CreateFromDiscriminatorValue); } },
                { "devices", n => { Devices = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "friend_devices", n => { FriendDevices = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "_id", n => { Id = n.GetStringValue(); } },
                { "mail", n => { Mail = n.GetStringValue(); } },
                { "timeline_not_read", n => { TimelineNotRead = n.GetIntValue(); } },
                { "timeline_size", n => { TimelineSize = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NetatmoClient.Models.NAUserAdministrative>("administrative", Administrative);
            writer.WriteObjectValue<global::NetatmoClient.Models.NADate>("date_creation", DateCreation);
            writer.WriteCollectionOfPrimitiveValues<string>("devices", Devices);
            writer.WriteCollectionOfPrimitiveValues<string>("friend_devices", FriendDevices);
            writer.WriteStringValue("_id", Id);
            writer.WriteStringValue("mail", Mail);
            writer.WriteIntValue("timeline_not_read", TimelineNotRead);
            writer.WriteIntValue("timeline_size", TimelineSize);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
