// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAWelcomeEvent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Camera that detected the event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CameraId { get; set; }
#nullable restore
#else
        public string CameraId { get; set; }
#endif
        /// <summary>Identifier of the event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>If person was considered away before being seen during this event</summary>
        public bool? IsArrival { get; set; }
        /// <summary>User facing event description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Id of the person the event is about (if any)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonId { get; set; }
#nullable restore
#else
        public string PersonId { get; set; }
#endif
        /// <summary>The snapshot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAWelcomeSnapshot? Snapshot { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAWelcomeSnapshot Snapshot { get; set; }
#endif
        /// <summary>Subtypes of SD and Alim events. Go to Welcome page for further details.</summary>
        public int? SubType { get; set; }
        /// <summary>Time of occurence of event</summary>
        public int? Time { get; set; }
        /// <summary>Type of events. Go to the Welcome page for further details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>Identifier of the video</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoId { get; set; }
#nullable restore
#else
        public string VideoId { get; set; }
#endif
        /// <summary>Status of the video (recording, deleted or available)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoStatus { get; set; }
#nullable restore
#else
        public string VideoStatus { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAWelcomeEvent"/> and sets the default values.
        /// </summary>
        public NAWelcomeEvent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAWelcomeEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAWelcomeEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAWelcomeEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "camera_id", n => { CameraId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_arrival", n => { IsArrival = n.GetBoolValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "person_id", n => { PersonId = n.GetStringValue(); } },
                { "snapshot", n => { Snapshot = n.GetObjectValue<global::NetatmoClient.Models.NAWelcomeSnapshot>(global::NetatmoClient.Models.NAWelcomeSnapshot.CreateFromDiscriminatorValue); } },
                { "sub_type", n => { SubType = n.GetIntValue(); } },
                { "time", n => { Time = n.GetIntValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "video_id", n => { VideoId = n.GetStringValue(); } },
                { "video_status", n => { VideoStatus = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("camera_id", CameraId);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_arrival", IsArrival);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("person_id", PersonId);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAWelcomeSnapshot>("snapshot", Snapshot);
            writer.WriteIntValue("sub_type", SubType);
            writer.WriteIntValue("time", Time);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("video_id", VideoId);
            writer.WriteStringValue("video_status", VideoStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
