// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAWelcomeHomeData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The global_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAWelcomeGlobalInfo? GlobalInfo { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAWelcomeGlobalInfo GlobalInfo { get; set; }
#endif
        /// <summary>The homes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NAWelcomeHome>? Homes { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NAWelcomeHome> Homes { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAWelcomeUser? User { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAWelcomeUser User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAWelcomeHomeData"/> and sets the default values.
        /// </summary>
        public NAWelcomeHomeData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAWelcomeHomeData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAWelcomeHomeData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAWelcomeHomeData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "global_info", n => { GlobalInfo = n.GetObjectValue<global::NetatmoClient.Models.NAWelcomeGlobalInfo>(global::NetatmoClient.Models.NAWelcomeGlobalInfo.CreateFromDiscriminatorValue); } },
                { "homes", n => { Homes = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomeHome>(global::NetatmoClient.Models.NAWelcomeHome.CreateFromDiscriminatorValue)?.AsList(); } },
                { "user", n => { User = n.GetObjectValue<global::NetatmoClient.Models.NAWelcomeUser>(global::NetatmoClient.Models.NAWelcomeUser.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::NetatmoClient.Models.NAWelcomeGlobalInfo>("global_info", GlobalInfo);
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomeHome>("homes", Homes);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAWelcomeUser>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
