// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace NetatmoClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NAWelcomeHome : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cameras property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NAWelcomeCamera>? Cameras { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NAWelcomeCamera> Cameras { get; set; }
#endif
        /// <summary>The events property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NAWelcomeEvent>? Events { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NAWelcomeEvent> Events { get; set; }
#endif
        /// <summary>Id of the home.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The modules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NAWelcomeModule>? Modules { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NAWelcomeModule> Modules { get; set; }
#endif
        /// <summary>Name of the home</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The persons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::NetatmoClient.Models.NAWelcomePerson>? Persons { get; set; }
#nullable restore
#else
        public List<global::NetatmoClient.Models.NAWelcomePerson> Persons { get; set; }
#endif
        /// <summary>The place property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::NetatmoClient.Models.NAWelcomePlace? Place { get; set; }
#nullable restore
#else
        public global::NetatmoClient.Models.NAWelcomePlace Place { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::NetatmoClient.Models.NAWelcomeHome"/> and sets the default values.
        /// </summary>
        public NAWelcomeHome()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::NetatmoClient.Models.NAWelcomeHome"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::NetatmoClient.Models.NAWelcomeHome CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::NetatmoClient.Models.NAWelcomeHome();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cameras", n => { Cameras = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomeCamera>(global::NetatmoClient.Models.NAWelcomeCamera.CreateFromDiscriminatorValue)?.AsList(); } },
                { "events", n => { Events = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomeEvent>(global::NetatmoClient.Models.NAWelcomeEvent.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "modules", n => { Modules = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomeModule>(global::NetatmoClient.Models.NAWelcomeModule.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "persons", n => { Persons = n.GetCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomePerson>(global::NetatmoClient.Models.NAWelcomePerson.CreateFromDiscriminatorValue)?.AsList(); } },
                { "place", n => { Place = n.GetObjectValue<global::NetatmoClient.Models.NAWelcomePlace>(global::NetatmoClient.Models.NAWelcomePlace.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomeCamera>("cameras", Cameras);
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomeEvent>("events", Events);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomeModule>("modules", Modules);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::NetatmoClient.Models.NAWelcomePerson>("persons", Persons);
            writer.WriteObjectValue<global::NetatmoClient.Models.NAWelcomePlace>("place", Place);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
